site_name: Sxrhhh 的个人小站
site_url: http://www.sxrhhh.top


nav:
  - 主页: index.md
  - 博客: 
    - 博客主页: blog/index.md
  - 网站词云: tags.md
  - 想法: 
    # - 想法: idea/index.md
    # - 2023 个人年度总结: idea/2023个人年度总结.md
    - 想法: idea/index.md

  - 关于本站: about.md
  - test:
    - test: test/index.md
    - 2a22: test/222.md
    - 1a11: test/111.md

  


theme:
  name: material
  language: zh  # 设置语言为中文
  custom_dir: overrides
  palette:
    # 切换为浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # 切换为深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs # 使分类具有选型卡结构
    - navigation.tabs.sticky  # 选项卡冻结,始终可见
    - navigation.path # 文章显示导航路径
    - navigation.top  # 回到顶部
    - navigation.indexes  # 合并一级目录导览

    - content.code.copy # 启用代码块复制
    - content.code.annotate # 启用代码注释


    - navigation.instant  # 启用即时加载
    - navigation.instant.progress

plugins:
  - search
  - blog:  # 内置博客插件
      post_excerpt: required  # 强制使用摘录
      blog_toc: true  # 可以使用目录查看帖子
    
  - blog:
      blog_toc: true
      blog_dir: idea

  - tags:
      tags_file: tags.md

  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  
    
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: 永久链接
      slugify: !!python/object/apply:pymdownx.slugs.slugify # 用slug替换toc链接
        kwds:
          case: lower

  - pymdownx.arithmatex:
      generic: true

  # 任务列表
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

  # 语法高亮代码块
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 内容选项卡
  - pymdownx.tabbed:
      alternate_style: true

  # 增加markdown语法
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # 用于html中的md语法,包括注释
  - attr_list
  - md_in_html

  # 启用图标
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # 启用告诫
  - admonition
  - pymdownx.details

extra_javascript:
  - dist/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

copyright: 版权所有 &copy; 2023 - 2024 Sxrhhh

extra:
  social:
    - icon: material/rss
      link: https://www.sxrhhh.top/feed
      name: RSS 订阅

    
    - icon: material/email
      link: mailto:sxrhhh.live@outlook.com
      name: 邮我吧->sxrhhh.live@outlook.com

    - icon: fontawesome/brands/github
      link: https://github.com/cycode0527
      name: Github